<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGPihyGE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGPihyGE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGPihyGE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGPihyGE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGPihyGE\App_KernelDevDebugContainer([
    'container.build_hash' => 'GPihyGE',
    'container.build_id' => 'a966129e',
    'container.build_time' => 1580118720,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGPihyGE');
